#!/bin/sh

##
# Quickstart
#
# Install our favorite free open source programs that we want running ASAP.
# We also install these in our other files here too, for completeness.
##

# Terminal via iTerm2
brew install --cask iterm2

# SSH via Eternal Terminal
brew install MisterTea/et/et

# Editor
brew install --cask vim

# Integrated Development Environment
brew install --cask zed

# Browser
brew install --cask firefox

# Messaging
brew install element

# Virtual private network
brew install --cask surfshark

# Log file viewer
brew install lnav

# Knowledge base
brew install --cask obsidian

# Version manager
brew install mise

# Prompt
brew install starship

# File transfer
brew install croc
