#!/bin/sh

##
# brew-install-favorites-with-prompts
#
# Use Homebrew to install our favorite packages for macOS,
# that may need to be installed manually because of prompts.
# The prompts may be for passwords, or for moving files, or for
# more-complex issues that need a human decision.
#
# ## Tracking
#
# * Package: https://github.com/sixarm/brew-install-favorites
# * Version: 6.0.0
# * Created: 2016-10-11T19:23:52Z
# * Updated: 2022-06-20T17:44:09Z
# * License: [GPL-2.0](https://spdx.org/licenses/GPL-2.0-only.html)
# * Contact: [Joel Parker Henderson](http://joelparkerhenderson.com)
##

##
# Communication
##

# Zoom video calling
brew install --cask zoom

##
# Environment
##

# DisplayLink enables adding monitors
brew install --cask displaylink

# Java language for running many applications
brew install --cask java

# Karabiner remaps keyboard keys
brew install --cask karabiner

## Misc

brew install --cask flip4mac
brew install --cask google-hangouts
brew install --cask inky
brew install --cask node
brew install --cask obs
brew install --cask pandoc
brew install --cask prey
brew install --cask seil
brew install --cask teamviewer
brew install --cask unity-web-player
brew install --cask unity3d
