#!/bin/sh

##
# OmniGroup
#
# OmniGroup provides paid software suitable for professional users.
#
# ## Tracking
#
# * Package: https://github.com/sixarm/brew-install-favorites
# * Version: 6.0.0
# * Created: 2016-10-11T19:23:52Z
# * Updated: 2022-06-20T17:44:09Z
# * License: [GPL-2.0](https://spdx.org/licenses/GPL-2.0-only.html)
# * Contact: [Joel Parker Henderson](http://joelparkerhenderson.com)
##

# OmniFocus: task list manager
brew install --cask omnifocus

# OmniGraffle: diagramming
brew install --cask omnigraffle

# OmniPlan: project management
brew install --cask omniplan

# OmniOutliner: writing organizer
brew install --cask omnioutliner
