#!/bin/sh

##
# brew-install-favorites-with-prompts
#
# Use Homebrew to install our favorite packages for macOS,
# that may need to be installed manually because of prompts.
# The prompts may be for passwords, or for moving files, or for
# more-complex issues that need a human decision.
#
# ## Tracking
#
# * Package: https://github.com/sixarm/brew-install-favorites
# * Version: 3.1.0
# * Created: 2017-01-01
# * Updated: 2020-06-20
# * License: [GPL-2.0](https://spdx.org/licenses/GPL-2.0-only.html)
# * Contact: [Joel Parker Henderson](http://joelparkerhenderson.com)
##

# Update - this is always the first step
brew update

## Environment-related

# DisplayLink enables adding monitors
brew cask install displaylink

# Java language for running many applications
brew cask install java

# Karabiner remaps keyboard keys
brew cask install karabiner

## Media-related

# Adobe Air player for multimedia content
brew cask install adobe-air

# Adobe Reader for PDF files
brew cask install adobe-reader

##
# Productivity
##

# Microsoft Office
# https://www.office.com/
brew cask install microsoft-office

## Misc

brew cask install flip4mac
brew cask install google-hangouts
brew cask install inky
brew cask install node
brew cask install obs
brew cask install pandoc
brew cask install prey
brew cask install seil
brew cask install teamviewer
brew cask install unity-web-player
brew cask install unity3d
brew cask install zoomus

## Cleanup - this is always the last step
brew cleanup
brew cask cleanup
