#!/bin/sh

##
# brew-install-favorites-for-stacks
#
# Use Homebrew to install our favorite tech-related packages
# that can be installed fully automatically i.e. unattended;
# these packages do not ask for passwords, do not have any
# prompts, and do not have any issues that need a human.
#
# If you're using this file and you find any packages that
# do not install automatically, please let us know by opening
# an issue, or emailing us, or creating a pull request. Thanks!
#
# ## Link
#
# Some of the brew packages need to link to others.
#
#   * `brew link cmake` before mysql
#   * `brew link cmake` before wireshark can be installed
#   * `brew link cmake` before homebrew/science/opencv
#   * `brew link pandoc` before shellcheck can be installed
#
# ## Tracking
#
# * Package: https://github.com/sixarm/brew-install-favorites
# * Version: 6.0.0
# * Created: 2016-10-11T19:23:52Z
# * Updated: 2022-06-20T17:44:09Z
# * License: [GPL-2.0](https://spdx.org/licenses/GPL-2.0-only.html)
# * Contact: [Joel Parker Henderson](http://joelparkerhenderson.com)
##

## Tap

# brew tap caskroom/cask
# brew tap homebrew/binary
# brew tap homebrew/brewdler
# brew tap homebrew/core
# brew tap homebrew/dupes
# brew tap homebrew/fuse
# brew tap homebrew/versions
# brew tap jingweno/ccat

##
# System
##

# XQuartz provides X.Org X Window System that runs on macOS.
brew install --cask xquartz

# Qt toolkit Cross-platform development of UIS and apps.
brew install qt5
brew install pyqt

##
# Environment
##

# Command-line programs for manipulating fonts.
brew install lcdf-typetools

# ASDF environment manager similar to nvm, rbenv, pipenv.
brew install coreutils &&
brew install curl &&
brew install git &&
brew install asdf

# Fast copy that's a modern version of `cp`.
brew install fcp

##
# Shell
##

# GUI for rsync.
brew install grsync

# Shell script syntax check linter.
brew install pandoc && brew link pandoc && 
brew install shellcheck

# WesTerm Rust terminal
brew tap wez/wezterm && 
brew install --cask wez/wezterm/wezterm

##
# Clients
##

# Shuttle: simple SSH shortcut menu.
brew install --cask shuttle

# Fugu: a graphical shell for SSH and FTP.
brew install --cask fugu

# Charles: enables a developer to view HTTP traffic.
brew install --cask charles

# Postman HTTP API monitoring tool.
brew install --cask postman

# Insomnia HTTP REST client for developers. 
brew install --cask insomnia

# Brow.sh web browser that uses text.
brew tap browsh-org/homebrew-browsh &&
brew install browsh

# Hurl is a client for HTTP testing.
brew tap jcamiel/hurl &&
brew install hurl

# OpenAPI Generator CLI
brew install openapi-generator

##
# Versioning
##

# SourceTree graphic client for git
brew install --cask sourcetree

# GitUp friendly Git interface and visualizer
brew install --cask gitup

# GitHub Desktop friendly Git GUI
brew install --cask github

# Meld visual diff merge tool
brew install --cask meld

# Filter a repo in a fast safe way
brew install git-filter-repo

# LazyGit is a git GUI that is designed to be fast and simple
brew tap jesseduffield/lazygit &&
brew install lazygit

##
# Languages
##

# Apache Maven is a software project management and comprehension tool.
brew install maven

# Apache Spark is for analytics
brew install apache-spark

# Apache Top command
brew install apachetop

# Apache Portable Runtime (APR)
brew install apr
brew install apr-util

##
# Mac programming
##

# Dash documentation browser and code snippet manager
brew install --cask dash

# Realm browser for the Realm embedded database
brew install --cask realm-browser

# Tunnelblick remote access VPN
brew install --cask tunnelblick

##
# Networking
##

# prettyping: ping with colorful output and progress bars
brew install prettyping

# HTTPie: Modern command line HTTP client
brew install httpie

# Wireshark network monitoring, with the QT GUI.
brew install qt &&
brew install cmake && brew link cmake && 
brew install --cask wireshark --with-qt

# Monit is for managing and monitoring Unix systems.
brew install monit

# Nagios IT infrastructure monitoring.
brew install nagios

# Wireshark-chmodbft enables regular users to capture network packets.
brew install --cask wireshark-chmodbpf

# Charles web debugging proxy
brew install --cask charles

# Siege is an http load testing and benchmarking utility.
brew install siege

##
# Server-related
##

# Consul tool for discovering and configuring services
brew install consul

# NGINX web server, with Ruby passenger middleware.
brew install nginx --with-passenger

# Varnish reverse-proxy web application accelerator.
brew install varnish

# Memcached is an in-memory cache server.
brew install libmemcached
brew install memcached

# Thrift is a protocol for serializing structured data; compare profobut.
brew install thrift

# Protocol buffers for serializing structured data; compare thrift.
brew install protobuf

# Consul tool for discovering and configuring services in your infrastructure
brew install consul

# Monit is for managing and monitoring Unix systems.
brew install monit

# Nagios IT infrastructure monitoring.
brew install nagios

# NGINX web server.
brew install nginx

# Varnish reverse-proxy web application accelerator.
brew install varnish

##
# Virtual environments
##

# Docker software containers to help distribute applications.
brew install docker
brew install boot2docker

# Docker Compose is a tool for defining and running multi-container Docker applications.
brew install docker-compose

# Docker Machine installs Docker Engine on virtual hosts, and manages the hosts.
brew install docker-machine

# Podman is daemonless container engine for developing, managing, and running containers.
brew install podman

# Vagrant creates and configures portable development environments.
brew install --cask vagrant
brew install --cask vagrant-manager

# VirtualBox creates and configures portable development environments, by Oracle.
brew install --cask virtualbox

# Parallels runs alternative operating systems
brew install --cask parallels

# Terraform common configuration to launch infrastructure.
brew install terraform

# corectl provides CoreOS over macOS made very simple
brew install --cask corectl

# Kubernetes Solo cluster for macOS
brew install --cask kube-solo

# WASMer Rust WASM runtime
brew install wasmer

##
# Editors
##

# Emacs editor
brew install --cask emacs

# Emacs editor for Spacemacs
brew tap d12frosted/emacs-plus
brew install emacs-plus
brew linkapps emacs-plus

# Android Studio
brew install --cask android-studio

# Eclipse is a large programming IDE built on Java
brew install --cask eclipse-ide
brew install --cask eclipse-platform

# MacTex: LaTeX document preparation system with high-quality typesetting.
brew install --cask mactex

# MacVIM
brew install --cask macvin

# Sublime
brew install --cask sublime
brew install --cask sublime-text

# Visual Studio Code by Microsoft
brew install --cask visual-studio-code

##
# Fonts
##

# Web font tools
brew install bramstein/webfonttools/sfnt2woff-zopfli
brew install bramstein/webfonttools/woff2

##
# Databases
#
# This section installs many databases and database tooling:
# Cassandra, CouchDB, Hadoop, MariaDB, MongoDB, PostgreSQL,
# RabbitMQ, Redis, Riak, Sphinx, SQLite. Notably *not* MySQL.
##

## Database-Related

# Cassandra database.
brew install cassandra

# CouchDB database, esp. for document-oriented storage.
brew install couchdb

# GNU dbm database functions
brew install gdbm

# Hadoop database.
brew install hadoop

# MariaDB database; prefer this over MySQL.
brew install mariadb

# MongoDB database.
brew install mongodb

# PostgreSQL database.
brew install postgresql

# PostgreSQL Geographic Information System
brew install postgis

# RabbitMQ enterprise message queue based on the emerging AMQP standard.
brew install rabbitmq

# Redis database, esp. for key-value cache and store, and data structures.
brew install redis

# Riak open-source distributed database.
brew install riak

# SQLite database: self-contained, serverless, zero-configuration, transactional engine.
brew install sqlite && 
brew link sqlite

# ZeroMQ message queue
brew install zeromq

## Database searchers

# Sphinx search engine.
brew install cmake &&
brew link cmake &&
brew install mysql &&
brew install postgresql && 
brew install sphinx

# GraphiQL: a lightweight Electron-based app wrapper around GraphiQL
brew install --cask graphiql

## Database managers

# MySQL Workbench database editor.
brew install cmake && brew link cmake
brew install --cask mysqlworkbench

# Realm browser mobile database editor.
brew install --cask realm-browser

# Sequel Pro database management application.
brew install --cask sequel-pro

# Toad database manager by Dell.
brew install --cask toad

# Valentina Studio database manager.
brew install --cask valentina-studio

##
# Data analytics
##

# Elasticsearch is a real-time, distributed storage, search, and analytics engine.
brew instal elasticsearch

# Logstash helps parse, enrich, transform, and buffer data from a variety of sources.
brew instal logstash

# Kibana is an open source analytics and visualization platform designed to work with Elasticsearch.
brew instal kibana

##
# Markup Tooling
#
# This section installs markup tooling.
# For example this section is a good place for HTML tools,
# Markdown tools, UML tools, XML tools, and similar.
##

# Pandoc converts among various formats, such as Markdown and HTML.
brew install pandoc

# Augeas configuration file parser.
brew install augeas

## Markdown

# MacDown simple markdown editor.
brew install --cask macdown

## UML

# StarUML modeling tool.
brew install --cask staruml

## XLS

# GNUmeric open soruce spreadsheet program.
brew install gnumeric

## XML

# XML converter.
brew install xmlstarlet

# Libxml2 is the XML C parser and toolkit.
brew install libxml2

# Libxslt is the XSLT C library for the XML EXtensible Stylesheet Language.
brew install libxslt

## HTML & CSS

# PUP command line HTML parser.
brew install https://raw.githubusercontent.com/EricChiang/pup/master/pup.rb

# Yahoo UI Compressor.
brew install yuicompressor

# Convert HTML to text
brew install html2text

# HTML compressor
brew install htmlcompressor --with-yuicompressor

##
# Programming Languages
#
# This section installs many programming languages:
# Clojure, Elixir, Erlang, Go, Haskell, Java, JavaScript,
# Perl, Python, R, Ruby, Scala, Swift, and tooling.
##

## Compilers

# LLVM cross-compiler
brew install homebrew/versions/llvm35

# Apple GCC (GNU C Compiler)
brew install apple-gcc42

# Valgrind suite of tools for debugging and profiling.
# Valkyrie is a Qt4-based GUI for the Memcheck and Helgrind tools in Valgrind.
# Uninstall these because they are currently incompatible with macOS 10.12
brew uninstall valkryrie; brew uninstall valgrind

## Android

# Android Software Development Kit (SDK) and Native Development Kit (NDK).
#
# Typically we configure our systems this way:
#
#     export ANDROID_SDK="/usr/local/Cellar/android-sdk/r17"
#     export ANDROID_NDK="/usr/local/Cellar/android-ndk/r7b"
#     export ANDROID_NDK_HOME="/usr/local/share/android-ndk"
#
brew install --cask android-sdk
brew install --cask android-ndk
brew install --cask android-studio

## Clojure

# Clojure programming language compiler.
brew install clojure-compiler

# Leiningen automates Clojure projects.
brew install leiningen

## Elixir

# Elixir programming language built on top of the Erlang VM.
brew install elixir

## Erlang

# Erlang programming language for scalable high-availability systems.
brew install erlang

## Yet Another Web Server
brew install yaws

## Go

# Go programming language by Google; compare `C`.
brew install go

## Haskell

# Cabal is a package manager for Haskell
brew install ghc cabal-install

## Java

# Java programming language
brew install --cask java

# Java programming language via OpenJDK
brew install --cask adoptopenjdk

# Gradle is a Java build tool
brew install gradle

# Maven is a Java build tool
brew install maven

# Spring Tool Suite is an Eclipse IDE for developing apps
brew install --cask sts

# Jetty provides a Java web server and javax.servlet container
brew install jetty

# Apache Tomcat implements Java Servlet and JavaServer Pages technologies.
brew install tomcat

# Glassfish application server.
brew install glassfish

# Apache Ant automates software build processes.
brew install ant

# Apache Maven is a build automation tool used primarily for Java projects. 
brew install maven

# Gradle general-purpose build tool.
brew install gradle

## JavaScript

# Node.js is a JavaScript platform for building fast, scalable network app.
brew install node

# Yarn is a JavaScript package manager for fast, reliable, and secure dependency management. 
brew install yarm

# PhantomJS is a headless WebKit scriptable with a JavaScript API.
brew install phantomjs

# V8 JavaScript Engine.
brew install v8

# JSON output using the shell
brew install jo

# JID JSON explorer
brew tap simeji/jid && brew install jid

# JP is a command line JSON parser using JMES
brew tap jmespath/jmespath && brew install jp

## Lua

brew install lua

## Perl

# Perl programming language, esp. for systems administration.
brew install perl

# Perl-Compatible Regular Expressions pattern matching tools.
brew install pcre

# CPAN search for perl modules
brew install cpansearch

## Python

# Python programming language, esp. for systems scripting.
brew install python
brew install python3

## R

# R programming language, esp. for statistics.
brew install r

## Ruby

# chruby changes the current Ruby.
brew install chruby

# JRuby is a high performance, stable, fully threaded Java implementation of Ruby.
brew install jruby

# Ruby programming language; compare `perl`, `python`.
brew install ruby

# Tool to install various implementations of Ruby.
brew install ruby-install

# Passenger Ruby middleware
brew install passenger

## Rust

# Rust programming language
brew install rust

## Scala

# Scala programming language, that runs on top of the JVM.
#brew install scala

##
# Platforms
##

# Amazon Web Services (AWS) Command Line Interface (CLI)
brew install awscli

# AWS command line tools
brew tap wallix/awless &&
brew install awless

# Heroku app hosting
brew install heroku

##
# Art editors
##

# Xquartz
brew install --cask xquartz

# Tap GUI
brew tap homebrew/gui

# Gimp pixel-based image editor, similar to Adobe Photoshop
brew install --cask gimp

# Inkscape vector-based image  editor, similar to Adobe Illustrator
brew install --cask inkscape; brew install inkscape

# Shotcut movie editor
brew install --cask shotcut

# Image optimizer
brew cask imageoptim

# GNU Multiple Precision Arithmetic Library
brew install gmp

##
# TODO
#
# These items come from other people and other repos
##

brew install berkeley-db
brew install ccat
brew install chromedriver
brew install cscope
brew install dialog
brew install dirmngr
brew install dos2unix
brew install exercism
brew install fasd
brew install gettext
brew install ghostscript
brew install git-crypt
brew install gnupg
brew install gpg-agent
brew install gnupg2
brew install jbig2dec
brew install openssl
brew install nginx --with-passenger
brew install nvm
brew install otto
brew install packer
