#!/bin/sh

##
# Microsoft
##

# Microsoft Office (needs prompt)
sudo softwareupdate --agree-to-license --install-rosetta
brew install --cask microsoft-office

# Microsoft Teams for chat (needs prompt)
brew install --cask microsoft-teams
