#!/bin/sh

##
# Quickstart
#
# Install our favorite free open source programs that we want running ASAP.
# We also install these in our other files here too, for completeness.
##

# Editors
brew install --cask neovim
brew install --cask emacs-plus-app

# Terminals
brew install --cask iterm2
brew install --cask ghostty

# Fonts
brew install --cask font-fira-code-nerd-font
brew install --cask font-iosevka-term-nerd-font

# SSH via Eternal Terminal
brew install MisterTea/et/et

# Integrated Development Environment
brew install --cask visual-studio-code
brew install --cask zed

# Browsers
brew install --cask firefox
brew install --cask google-chrome

# Messaging
brew install element

# Virtual private network
brew install --cask surfshark

# Log file viewer
brew install lnav

# Knowledge base
brew install --cask obsidian

# Version manager
brew install mise

# Prompt
brew install starship

# File transfer
brew install croc

# Containers
brew install docker
brew install podman
