#!/bin/sh

##
# brew-install-favorites-with-prompts
#
# Use Homebrew to install our favorite packages for macOS,
# that may need to be installed manually because of prompts.
# The prompts may be for passwords, or for moving files, or for
# more-complex issues that need a human decision.
#
# ## Tracking
#
# * Package: https://github.com/sixarm/brew-install-favorites
# * Version: 3.1.0
# * Created: 2017-01-01
# * Updated: 2020-06-20
# * License: [GPL-2.0](https://spdx.org/licenses/GPL-2.0-only.html)
# * Contact: [Joel Parker Henderson](http://joelparkerhenderson.com)
##

# Update - this is always the first step
brew update

##
# Communication
##

# Zoom video calling
brew install --cask zoom

##
# Environment
##

# DisplayLink enables adding monitors
brew install --cask displaylink

# Java language for running many applications
brew install --cask java

# Karabiner remaps keyboard keys
brew install --cask karabiner

##
# Productivity
##

# Microsoft Office
# https://www.office.com/
brew install --cask microsoft-office

# Microsoft Teams for chat
brew install --cask microsoft-teams

## Misc

brew install --cask flip4mac
brew install --cask google-hangouts
brew install --cask inky
brew install --cask node
brew install --cask obs
brew install --cask pandoc
brew install --cask prey
brew install --cask seil
brew install --cask teamviewer
brew install --cask unity-web-player
brew install --cask unity3d

## Cleanup - this is always the last step
brew cleanup
brew cask cleanup
