#!/bin/sh

##
# JetBrains
#
# JetBrains is paid software suitable for professional programmers,
# such as Integrated Development Environments (IDEs) for popular
# programming languages, including Java, Python, Ruby, PHP, etc.
##

# JetBrains Toolbox manages all the JetBrains software
brew install --cask jetbrains-toolbox

##
# If you prefer to install software individually,
# then you can uncomment any of the software below.
##

# AppCode Swift IDE
brew install --cask appcode

# CLion C/C++ IDE
brew install --cask clion

# DataGrip SQL IDE
brew install --cask datagrip

# IntelliJ Java IDE
brew install --cask intellij-idea

# PhpStorm PHP IDE
brew install --cask phpstorm

# PyCharm Python IDE
brew install --cask pycharm

# RubyMine Ruby IDE
#brew install --cask rubymine

# WebStorm IDE
brew install --cask webstorm
