#!/bin/sh

##
# iOS, Swift, Objective-C, Xcode, etc.
##

# Appium test automation framework
brew install --cask appium

# Carthage Xcode project dependency manager.
brew install carthage

# Command-line application launcher for the iOS Simulator
brew install ios-sim

# Tool to help with Swift style and conventions.
brew install swiftlint

# SourceKitten attaches to SourceKit AST.
brew install sourcekitten
