#!/bin/sh

##
# OmniGroup
#
# OmniGroup provides paid software suitable for professional users.
##

# OmniFocus: task list manager
brew install --cask omnifocus

# OmniGraffle: diagramming
brew install --cask omnigraffle

# OmniPlan: project management
brew install --cask omniplan

# OmniOutliner: writing organizer
brew install --cask omnioutliner
