#!/bin/sh

##
# JetBrains
#
# JetBrains is paid software suitable for professional programmers,
# such as Integrated Development Environments (IDEs) for popular
# programming languages, including Java, Python, Ruby, PHP, etc.
#
# ## Tracking
#
# * Package: https://github.com/sixarm/brew-install-favorites
# * Version: 6.0.0
# * Created: 2016-10-11T19:23:52Z
# * Updated: 2022-06-20T17:44:09Z
# * License: [GPL-2.0](https://spdx.org/licenses/GPL-2.0-only.html)
# * Contact: [Joel Parker Henderson](http://joelparkerhenderson.com)
##

# JetBrains Toolbox manages all the JetBrains software
brew install --cask jetbrains-toolbox

##
# If you prefer to install software individually,
# then you can uncomment any of the software below.
##

# AppCode Swift IDE
brew install --cask appcode

# CLion C/C++ IDE
brew install --cask clion

# DataGrip SQL IDE
brew install --cask datagrip

# IntelliJ Java IDE
brew install --cask intellij-idea

# PhpStorm PHP IDE
brew install --cask phpstorm

# PyCharm Python IDE
brew install --cask pycharm

# RubyMine Ruby IDE
brew install --cask rubymine

# WebStorm IDE
brew install --cask webstorm
