#!/bin/sh

##
# Microsoft
##

# Microsoft software may need Rosetta 2 for compatibility with Apple Silicon Macs.
sudo softwareupdate --agree-to-license --install-rosetta

# Microsoft Office (needs prompt)
brew install --cask microsoft-office

# Microsoft Teams for chat (needs prompt)
brew install --cask microsoft-teams
